ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  CRService:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: custom runtime demo
      Role: >-
        acs:ram::1244797166814602:role/aliyunfcgeneratedrole-cn-beijing-crservice
      LogConfig:
        Project: sealyun
        Logstore: robot
      InternetAccess: false
    robot:
      Type: 'Aliyun::Serverless::Function'
      Properties:
        Description: demo with custom runtime
        Handler: index.handler
        Runtime: custom
        Timeout: 10
        MemorySize: 128
        EnvironmentVariables:
          GITHUB_PASSWD: f975494768
          GITHUB_USER: sealrobot
          LD_LIBRARY_PATH: >-
            /code/.fun/root/usr/lib:/code/.fun/root/usr/lib/x86_64-linux-gnu:/code/.fun/root/lib/x86_64-linux-gnu:/code/.fun/root/usr/lib64:/code:/code/lib:/usr/local/lib
          PATH: >-
            /code/.fun/root/usr/local/bin:/code/.fun/root/usr/local/sbin:/code/.fun/root/usr/bin:/code/.fun/root/usr/sbin:/code/.fun/root/sbin:/code/.fun/root/bin:/code/.fun/python/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin
          PYTHONUSERBASE: /code/.fun/python
      Events:
        http_t:
          Type: HTTP
          Properties:
            AuthType: anonymous
            Methods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
