ROSTemplateFormatVersion: '2015-09-01'
Transform: 'Aliyun::Serverless-2018-04-03'
Resources:
  CRService:
    Type: 'Aliyun::Serverless::Service'
    Properties:
      Description: custom runtime demo
      InternetAccess: true
